### ISSUE TITLE
Monte-Carlo Template Project Missing

### ISSUE THREAD

**Issue by MeltyMakes** [alimousavifar/lab2_public#1]
Looks like the template folder for the Monte-Carlo half of the project is missing. https://github.com/alimousavifar/lab2_public#estimating-pi suggests it should be here.

Far from a huge deal but might be worth adding before we get some piazza posts about it :)

**Comment by alimousavifar** [comment]
Tnx. Added the template

**Comment by MeltyMakes** [comment]
Thank you!
